# Generated by Django 3.2.6 on 2021-08-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='課程名稱')),
                ('is_acvite', models.BooleanField(default=True, verbose_name='啟用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建檔日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='學校名稱')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建檔日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='教師姓名')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='連絡電話')),
                ('is_acvite', models.BooleanField(default=True, verbose_name='啟用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建檔日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='學生姓名')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='連絡電話')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('grade', models.SmallIntegerField(default=0, verbose_name='年級')),
                ('is_acvite', models.BooleanField(default=True, verbose_name='啟用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建檔日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.school')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_acvite', models.BooleanField(default=True, verbose_name='啟用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建檔日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.teacher'),
        ),
    ]
