# Generated by Django 3.2.6 on 2021-08-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210825_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=40, verbose_name='課程名稱'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='學校名稱'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='學生姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='教師姓名'),
        ),
    ]
