# Generated by Django 3.2.6 on 2021-08-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20210825_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '課程', 'verbose_name_plural': '課程'},
        ),
        migrations.AlterModelOptions(
            name='coursemember',
            options={'verbose_name': '課程名單', 'verbose_name_plural': '課程名單'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '學生', 'verbose_name_plural': '學生'},
        ),
        migrations.AddField(
            model_name='student',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='連絡電話2'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='連絡電話3'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='連絡電話4'),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('1', '國小一年級'), ('2', '國小二年級'), ('3', '國小三年級'), ('4', '國小四年級'), ('5', '國小五年級'), ('6', '國小六年級'), ('7', '國中一年級'), ('8', '國中二年級'), ('9', '國中三年級'), ('A', '高中一年級'), ('B', '高中二年級'), ('C', '高中三年級')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='連絡電話1'),
        ),
    ]
