# Generated by Django 3.2.6 on 2021-09-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20210924_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_with',
            field=models.DateTimeField(null=True, verbose_name='結束日期'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_with',
            field=models.DateTimeField(null=True, verbose_name='開始日期'),
        ),
    ]
