databases:
  - name: axl_demo
    plan: free
    databaseName: axl_demo
    user: axl_demo_user

services:
  - type: web
    plan: free
    name: answer
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn answer.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: axl_demo
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4